{
  "openapi": "3.0.3",
  "info": {
    "title": "IceCreamMC API",
    "version": "2.0"
  },
  "servers": [
    {
      "url": "https://ice-cream-api.vercel.app"
    },
    {
      "url": "http://localhost:3000"
    }
  ],
  "tags": [
    {
      "name": "Query",
      "description": "Query data in database"
    },
    {
      "name": "Commit",
      "description": "Submit data to database"
    },
    {
      "name": "Download",
      "description": "download file"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "apiKey",
        "in": "header",
        "name": "Authentication"
      }
    }
  },
  "paths": {
    "/v2/projects": {
      "get": {
        "summary": "Get project list",
        "tags": [
          "Query"
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "repo": {
                        "type": "string"
                      },
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "repo": "Example/projectName",
                    "id": "project",
                    "name": "projectName"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}": {
      "get": {
        "summary": "Get information about a specified project",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_groups": {
                        "type": "array"
                      },
                      "versions": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version_groups": [
                    "1.20"
                  ],
                  "versions": [
                    "1.20.4"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}": {
      "get": {
        "summary": "Get information about the specified version of the specified project",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version": "1.20",
                  "builds": [
                    1,
                    2,
                    3
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds": {
      "get": {
        "summary": "Get the Build information of the specified version of the specified project",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version": "1.20",
                  "builds": [
                    {
                      "build": 1,
                      "time": "2023-08-03T06:12:14.887Z",
                      "channel": "default",
                      "promoted": false,
                      "changes": [
                        {
                          "commit": "hash",
                          "summary": "string",
                          "message": "string"
                        }
                      ],
                      "downloads": {
                        "application": {
                          "name": "xxx.jar",
                          "sha256": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "未找到",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds/{build}": {
      "get": {
        "summary": "获取指定项目的指定版本的指定Build的信息",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "build",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "build": {
                        "type": "integer"
                      },
                      "time": {
                        "type": "string"
                      },
                      "channel": {
                        "type": "string"
                      },
                      "promoted": {
                        "type": "boolean"
                      },
                      "changes": {
                        "type": "array"
                      },
                      "downloads": {
                        "type": "object"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version": "1.20",
                  "build": 1,
                  "time": "2023-08-03T06:12:14.887Z",
                  "channel": "default",
                  "promoted": false,
                  "changes": [
                    {
                      "commit": "hash",
                      "summary": "string",
                      "message": "string"
                    }
                  ],
                  "downloads": {
                    "application": {
                      "name": "xxx.jar",
                      "sha256": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "未找到",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/version_group/{family}": {
      "get": {
        "summary": "获取指定项目的指定版本组的所有子版本",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "family",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_group": {
                        "type": "string"
                      },
                      "versions": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version_group": "1.20",
                  "versions": [
                    "1.20.4"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/version_group/{family}/builds": {
      "get": {
        "summary": "获取指定项目的指定版本组的所有Build的信息",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "family",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_group": {
                        "type": "string"
                      },
                      "versions": {
                        "type": "array"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "icecream",
                  "project_name": "IceCream",
                  "version_group": "1.20",
                  "versions": [
                    "1.20.4"
                  ],
                  "builds": [
                    {
                      "build": 1,
                      "time": "2023-08-03T06:12:14.887Z",
                      "channel": "default",
                      "promoted": false,
                      "changes": [
                        {
                          "commit": "hash",
                          "summary": "string",
                          "message": "string"
                        }
                      ],
                      "downloads": {
                        "application": {
                          "name": "xxx.jar",
                          "sha256": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "未找到",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}": {
      "get": {
        "summary": "获取指定项目的指定版本的指定Build的信息",
        "tags": [
          "Download"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "build",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "download",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "301": {
            "description": "成功",
            "content": {
              "application/java-archive": {}
            }
          },
          "404": {
            "description": "未找到",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/commit/build": {
      "post": {
        "summary": "提交一个新Build到数据库",
        "tags": [
          "Commit"
        ],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "project_id": {
                    "type": "string"
                  },
                  "version": {
                    "type": "string"
                  },
                  "channel": {
                    "type": "string"
                  },
                  "changes": {
                    "type": "string"
                  },
                  "jar_name": {
                    "type": "string"
                  },
                  "sha256": {
                    "type": "string"
                  },
                  "tag": {
                    "type": "string"
                  }
                },
                "required": true
              },
              "example": {
                "project_id": "icecream",
                "version": "1.20.4",
                "channel": "default",
                "changes": "changes",
                "jar_name": "icecream-paperclip-1.20.4.jar",
                "sha256": "sha256",
                "tag": "1.20.4-aac961a"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Submitted successfully"
          },
          "400": {
            "description": "Request format error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  }
}
